name: Dynamic Template

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Update Dynamic Template"
        uses: "./"
        with:
          GLOBAL_TEMPLATE_REPOSITORY: varunsridharan/varunsridharan
          files: |
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}